spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/mysql-rodojacto
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=${JWT_SECRET:Y2hhbmdlLW1lLXBsZWFzZS1jaGFuZ2UtbWUtcGxlYXNlLWNoYW5nZS1tZS1zZWNyZXQta2V5LXZhbHVl}
app.jwt.expiration-ms=86400000
